config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/home/index', to: 'home#index'
  get '/home/show', to: 'home#show', as: "fav_show"
  get '/search', to: 'home#search', as: "search" 
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'
  post "home/add_to_fav/:id", to: "home#add_to_fav", as: "add_to_fav"
  delete "home/remove_from_fav/:id", to: "home#remove_from_fav", as: "remove_from_fav"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chanel.rb
class Chanel < ApplicationRecord
    has_many :shows
end

app/models/fav.rb
class Fav < ApplicationRecord
  belongs_to :user
  belongs_to :show
  enum status: [:favorite, :unfavorite]
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :chanel
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @shows = Show.all
    @fav = Fav.where(user_id: current_user.id, show_id: @shows.ids, status: 0)
  end

  def show
    @user = current_user.id
    @fav_shows ||= []
    @fav = Fav.where(user_id: @user, status: 0)
    @fav.each do |f|
      @fav_shows << Show.where(id: f.show_id)
    end
  end

  def add_to_fav
    id = params[:id].to_i
    @user = current_user.id
    @fav = Fav.find_by(user_id: @user, show_id: id)
    if @fav.blank?
      Fav.create(user_id: @user, show_id: id, status: 0)
    else
      @fu = Fav.find_by(user_id: @user, show_id: id)
      @fu.update(status: 0)
    end
    redirect_to fav_show_path
  end

  def remove_from_fav
    id = params[:id].to_i
    @user = current_user.id
    @fu = Fav.find_by(user_id: @user, show_id: id)
    @fu.update(status: 1)
    redirect_to fav_show_path
  end

  def search
    if params[:chanel].blank? && !params[:show].blank?
      @shows = Show.where("name LIKE ?", "%#{params[:show]}%")
    elsif params[:show].blank? && !params[:chanel].blank?
      @chanel = Chanel.where("name LIKE ?", "%#{params[:chanel]}%")
      @shows = Show.where(chanel: @chanel.ids)
    else
      @chanel = Chanel.where("name LIKE ?", "%#{params[:chanel]}%")
      @shows = Show.joins(:chanel).where('LOWER(shows.name) like (?) AND LOWER(chanels.name) like (?)', "%#{params[:show].downcase}%", "%#{params[:chanel].downcase}%")
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<div class="bg-dark site_main_footer" style="color:white; text-align:center;">
    &copy; This site is reserved by Abhishek.
</div>

app/views/home/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark menu_navbar_main">
  <div class="container-fluid">
    <a class="navbar-brand" href="/home/index" style="color:white;">TVShow</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 menu_navbar_ul">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/home/index">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/home/show">Show Favorite</a>
        </li>
        <li class="nav-item pt-2">
          <%= button_to "Logout", destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="search_form">
  <%= form_tag(search_path, method: :get) do %>
    <p>Show</p>
    <%= text_field_tag(:show, params[:show]) %>

    <p>Chanel</p>
    <%= text_field_tag(:chanel, params[:chanel]) %>

    <%= submit_tag ("Search") %>
  <% end %>
</div>

app/views/home/index.html.erb
<%= render "menu" %>
<h2 class="pt-3 pb-2" style="text-align:center;">TV Shows</h2>

<div class="chanel-show-div  pb-5"> 
    <% @shows.each do |s| %>
        <div class="card m-5">
            <div class="card-header">
                <h4><%= s.chanel.name %></h4>
            </div>
            <div class="card-body">
                <h5 class="card-title"><%= s.name %></h5>
                <p class="card-text"><%= s.time.strftime("%H:%M") %></p>
                <p><% (Time.now + 30*60).strftime("%H:%M") %></p>
                <div class="add_fav_button_div">
                    <%= button_to "Add to Favorite", add_to_fav_path(s) %>
                    <%= button_to "Remove from Favorite", remove_from_fav_path(s), method: :delete %>
                </div>
            </div>
        </div>
    <% end %>
</div>

<%= render "footer" %>

app/views/home/search.html.erb
<%= render "menu" %>
<h2 class="pt-3 pb-2" style="text-align:center;">TV Shows</h2>
<div class="chanel-show-div  pb-5"> 
    <% @shows.each do |s| %>
        <div class="card m-5">
            <div class="card-header">
                <h4><%= s.chanel.name %></h4>
            </div>
            <div class="card-body">
                <h5 class="card-title"><%= s.name %></h5>
                <p class="card-text"><%= s.time %></p>
                <div class="add_fav_button_div">
                    <%= button_to "Add to Favorite", add_to_fav_path(s) %>
                    <%= button_to "Remove from Favorite", remove_from_fav_path(s), method: :delete %>
                </div>
            </div>
        </div>
    <% end %>
</div>
<%= render "footer" %>

app/views/home/show.html.erb
<%= render "menu" %>

<h2 class="pt-3 pb-2" style="text-align:center;">This is Your Favorite Shows</h2>
<div class="chanel-show-div  pb-5"> 
    <% @fav_shows.each do |f| %>
        <% f.each do |fs| %>
            <div class="card m-5">
                <div class="card-header">
                    <h4><%= fs.chanel.name %></h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= fs.name %></h5>
                    <p class="card-text"><%= raw(fs.description) %></p>
                    <%= button_to "x", remove_from_fav_path(fs), method: :delete %>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

<%= render "footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TVShow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'style.css' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>